### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by shreyashm850** [ciurana2016/predict_stock_py#3]
I tried running the script and i get this error. please help

Using TensorFlow backend.
Traceback (most recent call last):
  File "E:\SM8\Projects\Stock Predictor\stock_predict.py", line 7, in <module>
    from keras.models import Sequential
  File "C:\Users\shreyash\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\__init__.py", line 2, in <module>
    from . import backend
  File "C:\Users\shreyash\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\__init__.py", line 67, in <module>
    from .tensorflow_backend import *
  File "C:\Users\shreyash\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

**Comment by shreyashm850** [comment]
I tried changing the backend theano, it gives the error:
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.

PS: I'm using python 3.6.0

**Comment by shreyashm850** [comment]
Got it!
