### ISSUE TITLE
Error for some quotes??

### ISSUE THREAD

**Issue by BasharAG** [ciurana2016/predict_stock_py#4]
So, I tried it with several quotes and it runs fine, but for some quotes, it doesn't work properly. For instance, in the case of $EARS stock, it gives values that the stock was never priced it ever. Also, when I plugin quotes like $NAKD, I get the following error:

```
Using TensorFlow backend.
Enter a stock quote from NASDAQ (e.j: AAPL, FB, GOOGL): NAKD
Epoch 1/200
Traceback (most recent call last):
  File "predict_stock.py", line 105, in <module>
    print stock_prediction()
  File "predict_stock.py", line 81, in stock_prediction
    model.fit(trainX, trainY, nb_epoch=200, batch_size=2, verbose=2)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 672, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1196, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 911, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 76, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 265, in on_epoch_end
    self.progbar.update(self.seen, self.log_values, force=True)
AttributeError: 'ProgbarLogger' object has no attribute 'log_values
```

Please note: I don't put $ before the quotes.

**Comment by ciurana2016** [comment]
The last error looks like a keras error, I found the following link:
https://github.com/fchollet/keras/issues/3657 maybe It can help you, I will
look the errors you have with EARS in detail soon.
